#!/usr/bin/env sh
set -eu

DG_PROJECT_ROOT="${DG_PROJECT_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"

if [ -f "$DG_PROJECT_ROOT/config/distrobox-gaming.env" ]; then
  # shellcheck disable=SC1091
  . "$DG_PROJECT_ROOT/config/distrobox-gaming.env"
fi

: "${DG_BOX_NAME:=gaming}"
: "${DG_IMAGE:=archlinux:latest}"

: "${DG_HOST_UID:=$(id -u)}"
: "${DG_HOST_GID:=$(id -g)}"
: "${DG_HOST_USER:=$(id -un)}"
: "${DG_HOST_GROUP:=$(id -gn)}"

: "${DG_DATA_ROOT:=/mnt/data}"
: "${DG_BOX_ROOT:=$DG_DATA_ROOT/distrobox/gaming}"
: "${DG_BOX_HOME:=$DG_BOX_ROOT}"

: "${DG_EMUDECK_ROOT:=/mnt/terachad/Emulators/EmuDeck}"
: "${DG_ROM_ROOT:=$DG_EMUDECK_ROOT/roms}"
: "${DG_ROM_HEAVY_ROOT:=$DG_EMUDECK_ROOT/roms_heavy}"
: "${DG_ROM_RARE_ROOT:=$DG_EMUDECK_ROOT/roms_rare}"
: "${DG_BIOS_ROOT:=$DG_EMUDECK_ROOT/Emulation/bios}"

: "${DG_PS4_ROM_ROOT:=$DG_ROM_RARE_ROOT/ps4}"
: "${DG_PS4_FIRMWARE_MODULES:=$DG_ROM_RARE_ROOT/ps4-firmware/11.00_sys_modules}"
: "${DG_SHADPS4_TITLE_ID:=CUSA00003}"
: "${DG_SHADPS4_GAME_DIR:=$DG_PS4_ROM_ROOT/$DG_SHADPS4_TITLE_ID}"
: "${DG_SHADPS4_GAME_BOOT:=$DG_SHADPS4_GAME_DIR/eboot.bin}"
: "${DG_SHADPS4_GAME_ARG:=$DG_SHADPS4_TITLE_ID}"
: "${DG_SHADPS4_PATCH_NAME:=Driveclub.xml}"
: "${DG_SHADPS4_PATCH_XML:=$DG_BOX_HOME/.local/share/shadPS4/patches/$DG_SHADPS4_PATCH_NAME}"
: "${DG_SHADPS4_QTLAUNCHER_ROOT:=$DG_BOX_HOME/tools/shadps4-qtlauncher}"
: "${DG_SHADPS4_QTLAUNCHER_RELEASE:=2026-04-12-51b62bd}"
: "${DG_SHADPS4_QTLAUNCHER_RELEASES_API:=https://api.github.com/repos/shadps4-emu/shadps4-qtlauncher/releases}"
: "${DG_SHADPS4_QTLAUNCHER_ASSET_NAME:=shadPS4QtLauncher-qt.AppImage}"
: "${DG_SHADPS4_QTLAUNCHER_BIN:=$DG_BOX_HOME/bin/shadps4-qtlauncher-current}"
: "${DG_SHADPS4_VERSIONS_ROOT:=$DG_BOX_HOME/.local/share/shadPS4QtLauncher/versions}"
: "${DG_SHADPS4_RELEASES_API:=https://api.github.com/repos/shadps4-emu/shadPS4/releases}"
: "${DG_SHADPS4_CHANNEL:=Pre-release}"
: "${DG_SHADPS4_MANAGED_BIN:=$DG_SHADPS4_VERSIONS_ROOT/$DG_SHADPS4_CHANNEL/Shadps4-sdl.AppImage}"
: "${DG_SHADPS4_BIN:=$DG_BOX_HOME/bin/shadps4-current}"
: "${DG_SHADPS4_CMD_ALIAS:=$DG_BOX_HOME/bin/shadps4}"
: "${DG_DOLPHIN_CONFIG_DIR:=$DG_BOX_HOME/.config/dolphin-emu}"
: "${DG_XEMU_CONFIG_DIR:=$DG_BOX_HOME/.config/xemu}"
: "${DG_XEMU_DATA_DIR:=$DG_BOX_HOME/.local/share/xemu}"
: "${DG_XEMU_CONFIG:=$DG_XEMU_CONFIG_DIR/xemu.toml}"
: "${DG_XEMU_BOOTROM_SOURCE:=$DG_BIOS_ROOT/mcpx_1.0.bin}"
: "${DG_XEMU_FLASHROM_SOURCE:=$DG_BIOS_ROOT/Complex_4627.bin}"
: "${DG_XEMU_HDD_SOURCE:=$DG_BIOS_ROOT/xbox_hdd.qcow2}"
: "${DG_XEMU_BOOTROM:=$DG_XEMU_CONFIG_DIR/mcpx_1.0.bin}"
: "${DG_XEMU_FLASHROM:=$DG_XEMU_CONFIG_DIR/Complex_4627.bin}"
: "${DG_XEMU_HDD:=$DG_XEMU_DATA_DIR/xbox_hdd.qcow2}"
: "${DG_XENIA_PREFIX:=$DG_BOX_HOME/wineprefixes/xenia-manager}"
: "${DG_XENIA_CACHE_DIR:=$DG_BOX_HOME/cache/xenia-manager}"
: "${DG_XENIA_MANAGER_RELEASES_DIR:=$DG_BOX_HOME/tools/xenia-manager/releases}"
: "${DG_XENIA_MANAGER_CURRENT:=$DG_BOX_HOME/tools/xenia-manager/current}"
: "${DG_XENIA_MANAGER_EXE:=$DG_XENIA_MANAGER_CURRENT/XeniaManager.exe}"
: "${DG_XENIA_MANAGER_BIN:=$DG_BOX_HOME/bin/xenia-manager}"
: "${DG_XENIA_MANAGER_RELEASE_API:=https://api.github.com/repos/xenia-manager/xenia-manager/releases/latest}"
: "${DG_XENIA_MANAGER_ZIP_URL:=}"
: "${DG_XENIA_DOTNET_URL:=https://aka.ms/dotnet/10.0/windowsdesktop-runtime-win-x64.exe}"
: "${DG_XENIA_VCREDIST_URL:=https://aka.ms/vs/17/release/vc_redist.x64.exe}"
: "${DG_XENIA_GAME_DIR:=$DG_ROM_ROOT/xbox360}"
: "${DG_DESKTOP_TEMPLATE_DIR:=$DG_PROJECT_ROOT/config/desktop/templates}"
: "${DG_DESKTOP_RENDER_DIR:=$DG_PROJECT_ROOT/config/desktop/rendered}"

: "${DG_LEGACY_DOCS_ROOT:=/mnt/terachad/Documents/FrankMD/Linux}"
: "${DG_HOST_APPLICATIONS_DIR:=$HOME/.local/share/applications}"

export DG_PROJECT_ROOT DG_BOX_NAME DG_IMAGE
export DG_HOST_UID DG_HOST_GID DG_HOST_USER DG_HOST_GROUP
export DG_DATA_ROOT DG_BOX_ROOT DG_BOX_HOME
export DG_EMUDECK_ROOT DG_ROM_ROOT DG_ROM_HEAVY_ROOT DG_ROM_RARE_ROOT DG_BIOS_ROOT
export DG_PS4_ROM_ROOT DG_PS4_FIRMWARE_MODULES
export DG_SHADPS4_TITLE_ID DG_SHADPS4_GAME_DIR DG_SHADPS4_GAME_BOOT DG_SHADPS4_GAME_ARG
export DG_SHADPS4_PATCH_NAME DG_SHADPS4_PATCH_XML
export DG_SHADPS4_QTLAUNCHER_ROOT DG_SHADPS4_QTLAUNCHER_RELEASE DG_SHADPS4_QTLAUNCHER_RELEASES_API
export DG_SHADPS4_QTLAUNCHER_ASSET_NAME DG_SHADPS4_QTLAUNCHER_BIN
export DG_SHADPS4_VERSIONS_ROOT DG_SHADPS4_RELEASES_API DG_SHADPS4_CHANNEL
export DG_SHADPS4_MANAGED_BIN DG_SHADPS4_BIN DG_SHADPS4_CMD_ALIAS
export DG_DOLPHIN_CONFIG_DIR
export DG_XEMU_CONFIG_DIR DG_XEMU_DATA_DIR DG_XEMU_CONFIG
export DG_XEMU_BOOTROM_SOURCE DG_XEMU_FLASHROM_SOURCE DG_XEMU_HDD_SOURCE
export DG_XEMU_BOOTROM DG_XEMU_FLASHROM DG_XEMU_HDD
export DG_XENIA_PREFIX DG_XENIA_CACHE_DIR DG_XENIA_MANAGER_RELEASES_DIR DG_XENIA_MANAGER_CURRENT
export DG_XENIA_MANAGER_EXE DG_XENIA_MANAGER_BIN DG_XENIA_MANAGER_RELEASE_API DG_XENIA_MANAGER_ZIP_URL
export DG_XENIA_DOTNET_URL DG_XENIA_VCREDIST_URL DG_XENIA_GAME_DIR
export DG_DESKTOP_TEMPLATE_DIR DG_DESKTOP_RENDER_DIR
export DG_LEGACY_DOCS_ROOT DG_HOST_APPLICATIONS_DIR
