---
- name: Ensure xemu config directory exists
  ansible.builtin.file:
    path: "{{ dg_xemu_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy xemu config from template
  ansible.builtin.template:
    src: xemu.toml.j2
    dest: "{{ dg_xemu_config }}"
    backup: true
    mode: "0644"
